const seed=[{id:crypto.randomUUID(),title:'Polish the onboarding flow',summary:'Review copy and tighten the first-run experience.',status:'active',messages:[['user','Review the onboarding flow and suggest the highest-impact improvements.'],['assistant','I found three opportunities: shorten the first prompt, move permissions after value is clear, and add a visible progress cue.']]},{id:crypto.randomUUID(),title:'Release checklist',summary:'Prepare the final checks for the 1.4 release.',status:'waiting',messages:[['user','Build a release checklist for this sprint.'],['assistant','The draft checklist is ready. I’m waiting on the final build number.']]},{id:crypto.randomUUID(),title:'API notes',summary:'Summarize the latest integration decisions.',status:'completed',messages:[['user','Summarize the API integration decisions.'],['assistant','Authentication stays at the edge, requests are idempotent, and retries use exponential backoff.']]}];
let sessions=JSON.parse(localStorage.getItem('dsh.sessions')||'null')||seed;let filter='all';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('dsh.sessions',JSON.stringify(sessions))}function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function row(s){const icon=s.status==='completed'?'✓':'ϟ';return `<button class="session-row" data-session="${s.id}"><span class="status-icon ${s.status}">${icon}</span><span class="session-copy"><b>${esc(s.title)}</b><p>${esc(s.summary)}</p></span><span class="chevron">›</span></button>`}
function render(){const visible=filter==='all'?sessions:sessions.filter(s=>s.status===filter);$('#recent-list').innerHTML=sessions.slice(0,3).map(row).join('');$('#all-list').innerHTML=visible.map(row).join('');$('#metric-sessions').textContent=sessions.length;$('#metric-active').textContent=sessions.filter(s=>s.status==='active').length;$('#metric-done').textContent=sessions.filter(s=>s.status==='completed').length;$$('[data-session]').forEach(b=>b.onclick=()=>openDetail(b.dataset.session))}
function showTab(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===id));window.scrollTo({top:0,behavior:'smooth'})}
function openDetail(id){const s=sessions.find(x=>x.id===id);if(!s)return;$('#detail-content').innerHTML=`<div class="detail-wrap"><p class="eyebrow">${s.status.toUpperCase()}</p><h2>${esc(s.title)}</h2><p class="summary">${esc(s.summary)}</p><div class="messages">${s.messages.map(m=>`<div class="bubble ${m[0]}">${esc(m[1])}</div>`).join('')}</div><form class="detail-form"><input name="message" placeholder="Continue the session..."><button>Send</button></form></div>`;const form=$('.detail-form');form.onsubmit=e=>{e.preventDefault();const input=form.message;const text=input.value.trim();if(!text)return;s.messages.push(['user',text],['assistant','I’ve queued that for this session. The next step is ready when you are.']);s.summary=text;s.status='active';save();render();openDetail(id)};$('#detail').showModal()}
$$('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$$('[data-action="new"]').forEach(b=>b.onclick=()=>{$('#prompt').value='';$('#composer').showModal()});$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#composer-form').onsubmit=e=>{e.preventDefault();const text=$('#prompt').value.trim();if(!text)return;const s={id:crypto.randomUUID(),title:text.slice(0,34),summary:text,status:'active',messages:[['user',text],['assistant','I’m ready. I’ll break this into a focused plan and keep you updated here.']]};sessions.unshift(s);save();render();$('#composer').close();showTab('sessions');openDetail(s.id)};render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');

